name: Deploy Portfolio to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci --legacy-peer-deps
      
      - name: Create Next.js config for GitHub Pages
        run: |
          echo "Creating Next.js config for GitHub Pages"
          cat > next.config.js << 'EOL'
          /** @type {import('next').NextConfig} */
          const nextConfig = {
            output: 'export',       // Important for static export
            images: { unoptimized: true },
            trailingSlash: true,
          };
          
          module.exports = nextConfig;
          EOL
      
      - name: Build and export static site
        run: |
          npm run build
          npm run export

      - name: Add .nojekyll and CNAME
        run: |
          touch out/.nojekyll
          echo "hmblecreator.github.io" > out/CNAME
      
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: out
  
  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
